### ISSUE TITLE
implement quicktime76

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/Scripts#118]
Needed for games like Audiosurf.

**Comment by Brainzyy** [comment]
@plata it seems like this was not implemented correctly. Audiosurf can't find Quicktime.

**Comment by plata** [comment]
I couldn't test it. Can you compare the implementation to the one of winetricks?

**Comment by Brainzyy** [comment]
@plata I think I know what was wrong. Quicktime gets installed silently here, no? That doesn't work with Quicktime.

**Comment by plata** [comment]
Yes it is silently (`/qn`). I just followed the winetricks way of doing it. Does it work if you remove the `/qn`?

**Comment by Brainzyy** [comment]
@plata That fixed it :D going to prep a PR
