### ISSUE TITLE
® ™ yes or no

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#137]
Where shall ® and ™ be used? Most scripts do not use it in the git directory name (except PAYDAY™ The Heist) but only in the script.js and application.json.

We should have a general rule for this.

**Comment by Brainzyy** [comment]
Agreed.

**Comment by plata** [comment]
@qparis can we take a decision and close this?

**Comment by qparis** [comment]
Currently, if application.json and the directory do not have the same name, the name in application.json will overwrite the name of the directory. 
I'd recommend to avoid special characters in directory name, but we can safely use them in the json file

**Comment by plata** [comment]
Updated [README](https://github.com/PlayOnLinux/Scripts/blob/master/README.md) and [wiki](https://github.com/PlayOnLinux/Scripts/wiki/application.json). Removed ™ from PAYDAY folder name (see #178)
