### ISSUE TITLE
QuickScript: add post install hook

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#15]
Add a post install hook (optional) to the QuickScript which is called after the installation but before the setup wizard is closed.

QuickScript:
```javascript
  that.postInstall = function(postInstall) {
    that._postInstall = postInstall;
    return that;
  };

  that.go = function() {
    // perform installation
    ...
    that._postInstall();
    setupWizard.close();
  }
```

**Comment by qparis** [comment]
Good idea !

**Comment by plata** [comment]
I need it for at least one script ;) (have to change a config file for Rocksmith 2014).
