### ISSUE TITLE
fix vcrun2008

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#153]
vcrun2008 is not working properly. I had to use winetricks to install vcrun2008 to make Quantum Conundrum work.

**Comment by plata** [comment]
It seems to install (if I run it again, it asks me to repair or uninstall). However, the dlls I would expect do not exist in system32.

**Comment by qparis** [comment]
Maybe the dlls need tonne removed before

**Comment by plata** [comment]
I tried that already.
