### ISSUE TITLE
Add PoL games to native Steam

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#154]
During installation of a Steam game, create a .desktop file which can be added to the native Steam client as [Non-Steam game](https://support.steampowered.com/kb_article.php?ref=2219-YDJV-5557).
The .desktop could run phoenicis-cli for the given shortcut.

**Comment by plata** [comment]
@qparis could you provide me with a description how to use phoenicis-cli?

**Comment by qparis** [comment]
Just run PlayOnLinuxCLI class
Have a look at CLIController to find available options

**Comment by plata** [comment]
Ok have it. However, phoenicis-cli is not currently included in phoenicis-dist so how can I run it? (It's working from within my IDE).

**Comment by qparis** [comment]
I'm not sure phoenicis-dist is the right solution to distribute POL

**Comment by plata** [comment]
No idea. I'm just trying to do something like:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Notepad++
Type=Application
Exec=java -classpath "/home/plata/POL-POM-5/phoenicis-dist/target/phoenicis-dist/" com.playonlinux.cli.PlayOnLinuxCLI -run Notepad++
```

**Comment by plata** [comment]
@qparis any plan how POL should be distributed? What about something like [jdeb](https://github.com/tcurdt/jdeb) to build .deb's in maven directly? Shall it be one package or several (like common, javafx, cli...)?

**Comment by qparis** [comment]
I think one package is a lot easier

**Comment by plata** [comment]
Good. I created an issue PlayOnLinux/POL-POM-5#551.

Would be really nice to have this (I'm not using PoL4 anymore and currently I start PoL5 from my IDE).

**Comment by plata** [comment]
There's a description how to do this in the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Run#Show-games-in-native-Steam).
