### ISSUE TITLE
Shortcut description file is empty

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#18]

**Comment by qparis** [comment]
Which file?

**Comment by plata** [comment]
.PlayOnLinux-5/shortcuts/app.description

**Comment by qparis** [comment]
It could, but the json is parsed on another level (by javascript typically), whereas the description is currently directly part of ShortcutDTO

**Comment by plata** [comment]
So we need to set the description twice? Once in the json and once in the script?

**Comment by qparis** [comment]
No you could read the json from the script

**Comment by qparis** [comment]
But you can also have some programs (like Office) that have many shortcuts for one script

**Comment by plata** [comment]
Ah. So it's really a description of the shortcut itself.
