### ISSUE TITLE
Information about the created shortcuts for the League of Legends BETA Client

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/Scripts#181]
During the installation of the League of Legends BETA client the script automatically creates two shortcuts. In addition the BETA client itself creates another shortcut after the installation finished.
When I wanted to start the client after the installation I was unsure which shortcut to use, because using the wrong one did nothing or gave me an error screen.
To solve this I would suggest adding a bit more information to the shortcuts, that tells the user what happens after he/she clicks on the shortcut.

In addition I believe that the created shortcut, that is created by League of Legends itself after the installation, doesn't work. I didn't take a closer look at it, but I guess it won't work because the wine stuff is missing?

**Comment by plata** [comment]
The ShortcutDTO supports a description. The question is where/how this should be shown. Probably it would be easier to use a better name for the shortcuts.

**Comment by madoar** [comment]
I must agree, I think a more descriptive name would solve the problem.

**Comment by plata** [comment]
The other possibility would be to simply run the launcher once during the installation so the LeagueClient.exe is downloaded. Then you would not need a second shortcut at all.

**Comment by madoar** [comment]
As far as I understood @feanor12 You must manually tell the League of Legends launcher to download the beta client. Only after doing this the `LeagueClient.exe` file will be created.
So we would need to add an additional condition to check if a `LeagueClient.exe` file was created.

**Comment by plata** [comment]
I see. So the launcher does not have command line parameters to initiate the download?

**Comment by plata** [comment]
Doesn't seem so.

I suggest to do this: Instead of having to shortcuts and explaining when to start which one, create a small batch script. This should execute the following pseudo code:
```
IF LeagueClient.exe exists
THEN run LeagueClient.exe
ELSE run lol.launcher.admin.exe
```

**Comment by feanor12** [comment]
The bat file would be a good solution, I think. On the other side, there is a way to get the LeagueClient.exe, but it is a bit more difficult and involves the rads user kernel, which distributes the files.

**Comment by plata** [comment]
I skimmed through the strings in the exe to search for command line options. I remember seeing something about RADS ("RADS\system\rads_user_kernel.exe" updateandrun lol_launcher LoLLauncher.exe). But didn't consider this as a possibility. If you think this could be used directly, that would probably be the finest solution of all.
BTW: How did you know this RADS stuff? Same way like me?

**Comment by feanor12** [comment]
https://github.com/Nefelim4ag/League-Of-Legends
I found this, but I just took a short look, as the other Methode appeared easier.

**Comment by plata** [comment]
Maybe it's not even that complicated after all. We do not need the whole wine setup etc which is done in that script. The whole download/setup of RADS is also not required as it already exists in the LoL folder. So maybe calling `RADS\system\updateandrun lol_launcher LoLLauncher.exe` is already sufficient.

**Comment by feanor12** [comment]
The other thing which was also in my mind was the fact that they are starting to set the new client as default. Maybe the installer will change again for that. Just installing the beta client.
http://euw.leagueoflegends.com/en/news/game-updates/features/client-beta-update-2-replacing-legacy-client

**Comment by plata** [comment]
Maybe the script needs to be updated again then. Could you try if it works by simply calling this RADS command and use the bat solution otherwise? Would be good if we could get rid of this issue (no one knows how/when they might change the launcher again).

**Comment by feanor12** [comment]
I'm not at my PC at the moment. So it will take a day or two.

**Comment by madoar** [comment]
I think it's quite likely that the script must be updated, when the new client is finally released. I wouldn't suggest to plan too far ahead, with the goal that the current script doesn't need to be changed.

**Comment by plata** [comment]
@feanor12 sure, take your time.

**Comment by feanor12** [comment]
At the moment I think the rads_user_kernel method will not work. If I do an update I only see the updateandrun lol_launcher ... command. The other commands like enumavailproj or installproj result in a 

`(  ERROR)[17:35:07.214] RADS::UserKernel::UserCommandThread::ThreadProc: Invalid command "enumavailproj"`

I also get this line 

`(  ERROR)[17:35:07.214] RADS::User::PandoManager::start: StartPMB failed, returned error 6
`
If I remember correctly, the PandoManager is part of the old patching system they wanted to get rid of.

**Comment by feanor12** [comment]
How do I start a bat file from a Wine shortcut?

**Comment by plata** [comment]
Never tried to run bat. I thought it would work the same way like an exe.

**Comment by feanor12** [comment]
I think I need something like
`wine cmd.exe /C runme.bat`

**Comment by qparis** [comment]
I think we should enhance wine runner so that it can run .bat and .msi files

**Comment by plata** [comment]
@qparis how should that look like?

**Comment by qparis** [comment]
Like this? Not sure if it will work

**Comment by plata** [comment]
What "this" do you refer to?

**Comment by plata** [comment]
@madoar this should be fixed by now, right?
