### ISSUE TITLE
Bat file execute not working

### ISSUE THREAD

**Issue by feanor12** [PlayOnLinux/Scripts#183]
I tested the bat file launcher and it almost works.

The start command wants a wine path.
So `wine start /home/user/...LoL/run.bat` does not work, but `wine start C:\LoL\run.bat` works.

Is there a function to convert the path like `winepath -w path`?

What also works is just running the bat file(`wine start run.bat`), if I'm in the correct directory.

**Comment by plata** [comment]
I don't think we have the winepath functionality already. But it should not be too difficult to implement a function in Wine/script.js which provides this (basically a wrapper for winepath).

Something like (untested):
```Javascript
Wine.prototype.winepath = function (path) {
    var winepathBinary = this._fetchLocalDirectory() + "/bin/winepath";
    var processBuilder = new java.lang.ProcessBuilder(Java.to([winepathBinary + " -w", path].concat(args), "java.lang.String[]"));
    this._process = processBuilder.start();
    return org.apache.commons.io.IOUtils.toString(this._process.getInputStream());
}
```
