### ISSUE TITLE
Age of Empires 2 HD not starting

### ISSUE THREAD

**Issue by Linkaan** [PlayOnLinux/Scripts#195]
I compiled the latest version of POL-POM-5 and tried installing AoE2HD both using the steam script and AoE2HD script but both gave the same result on my system.

I'm running Arch Linux 4.10.6-1 x86_64 with i3 WM on a Radeon RX 470 GPU. This is the error I receive when I start the game:

![Failed to load image 'C:\Program Files\Steam\steamapps\common\Age2HD\resources\_common\textures\ui\xcamdlg_stretched.png'](http://i.imgur.com/aoixwpL.png)

Although I could not get the game working with POL it is playable using wine standalone with winetricks. I got a similar error message at first when I installed wine 2.0 on my system but what I did was install d3dx9_43 with winetricks like so:
`winetricks d3dx9_43`
Now I was able to start the game and play singleplayer and multiplayer however I still have the following issues which is why I want to run POL to see if it works better:
- Sound is only coming from AoE2HD and I can't play youtube videos or use mumble etc. simultaneously.
- AoE2HD starts in the middle of my two monitors and only the half of the game is displayed. A workaround for this is to first disable one of my monitors with xrandr and then start the game and enable the monitor again.
- I want to have all my games in one place so POL is perfect for this.

Perhaps there is a way to install d3dx9_43 with POL?

**Comment by plata** [comment]
d3dx9_43 should be a verb. There's a description in the [wiki](https://github.com/PlayOnLinux/Scripts/wiki/Verbs) how to create verbs. 

I wonder why AoE II HD is working on my PC (Ubuntu 16.04) and not on yours.

**Comment by Linkaan** [comment]
Sorry for my ignorance but how do I install a verb? Not sure what it means.

**Comment by plata** [comment]
The verbs are installed by the script during the installation of an app. If you look e.g. at the [Quantum Conundrum script](https://github.com/PlayOnLinux/Scripts/blob/master/Games/Quantum%20Conundrum/Steam/script.js), you can see that it installs the `vcrun2008` Verb (which is defined [here](https://github.com/PlayOnLinux/Scripts/blob/master/Functions/Verbs/vcrun2008/script.js)) in the `preInstall`.

If you believe that `d3dx9_43` should be installed for AoEII HD, we will need a `d3dx9_43` verb and install it in a similar way. As stated in the [wiki](https://github.com/PlayOnLinux/Scripts/wiki/Verbs), it is possible to take the winetricks code as an example of how the verb should look like.

As I said, the game is working for me as it is now, so I cannot test if/why `d3dx9_43` helps.

**Comment by plata** [comment]
@Linkaan any news on this issue?

**Comment by Linkaan** [comment]
@plata I installed Linux Mint and could run the aoe2 script without any problems and without installing d3dx9_43 it worked. So it was probably something to do with my Arch Linux installation. I'm closing this issue now.

**Comment by plata** [comment]
Ok, great!

**Comment by TimHi** [comment]
Had the exact same issue with the missing image, installing d3dx9_43 with winetricks fixed this for me. 
I'm running Arch aswell.

**Comment by plata** [comment]
Ok... Would be interesting to know why Arch needs d3dx9_43. As long as we do not know that, we cannot know how this should be handled. The same error could happen also with other applications on Arch.

**Comment by TimHi** [comment]
I honestly can't tell you, i just stumbled across this issue and wanted to share the working fix for me

**Comment by rafed123** [comment]
@TimHi Thanks dude! This worked for me on Kali!! :)

**Comment by plata** [comment]
Mh. If this issue exists also on other systems, we should maybe really consider to just install d3dx. The existing [d3dx9 Verb](https://github.com/PhoenicisOrg/scripts/blob/master/Engines/Wine/Verbs/d3dx9/script.js) should do.

@TimHi @rafed123 can anyone of you test that and provide a pull request if it helps? You just have to add the include (`include(["engines", "wine", "verbs", "d3dx9"]);` and then add the Verb installation to `postInstall` (`wine.d3dx9();`).

**Comment by karlosss** [comment]
@TimHi ran into the same Arch issue, installing d3dx9_43 works, but makes the game run like 5 fps on my T420. Yours is working fine?

Do we have any ideas why Arch needs this, while other distros seem not to?

**Comment by TimHi** [comment]
@karlosss It's been a while since i last played it, but back then it was fine

**Comment by karlosss** [comment]
I finally got it. On Arch, use Wine version 4.0-rc7-staging and no winetricks are needed.

**Comment by plata** [comment]
Do you think the script should be updated? If so, would 4.8 also work?

**Comment by karlosss** [comment]
@plata I am using ArchLinux, so what I say here might not be true in general, but 4.8 on Arch results in a black screen with only the mouse pointer visible since the game starts. A friend of mine having Arch as well experienced the same behavior.

Anyway, I have not tested 4.0-rc7-staging on other systems than Arch (since I do not have then installed) so I cannot say it should be updated, since it might break on other distros.

**Comment by ImperatorS79** [comment]
@karloss Might be worth to record a log of wine to see why 4.8 does not work.

**Comment by plata** [comment]
Last time I played AoE 2 HD was on Manjaro using Steam play so maybe proton could be an alternative (I'm hesitating to change a script to use Wine staging).
