### ISSUE TITLE
Wine Virtual Desktop configuration

### ISSUE THREAD

**Issue by odziom91** [PlayOnLinux/Scripts#211]
Hello!
Is it possible to create prefixes with Virtual Desktop resolution setup in Wine Configuration?
Some games need Virtual Desktop option for correct recognize screen resolution, for example Stronghold game:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=32700

**Comment by plata** [comment]
This is not yet implemented. It has to be done in a similar way to `setSoundDriver` in `Functions/Engines/Wine/script.js`. If you know the registry entries which have to be changed, it should be quite easy.

**Comment by plata** [comment]
Just checked <https://wiki.winehq.org/Useful_Registry_Keys>: Should be HKEY_CURRENT_USER/Software/Wine/Direct3D/Explorer/Desktops

**Comment by odziom91** [comment]
It looks good. How to call a function from Functions/Engines/Wine/script.js in installation script?

**Comment by plata** [comment]
Use the pre/postInstall. You can check the [Rocksmith 2014 script](https://github.com/PlayOnLinux/Scripts/blob/master/Games/Rocksmith%202014/Steam/script.js) as an example.

**Comment by odziom91** [comment]
Ok, it works. I wrote function for Wine's scripts.js - setVirtualDesktop = function (width, height).
I will create a pull request in some minutes for that. Please check that everyting is ok or make changes if something is wrong.

**Comment by plata** [comment]
fixed by #219
