### ISSUE TITLE
Age of Empires II HD doesn't load without launcher rename

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/Scripts#233]
If I were a user, I'd be very confused when Age of Empires II does not launch when I ask it to. The launcher (~/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/steamapps/common/Age2HD/AoK HD.exe) has to be renamed 'Launcher.exe' (and the other 'Launcher.exe' has to be renamed 'Launcher.exe.bak' or deleted) for Age of Empires II HD to launch.

If there's not a way to script this, since it has to happen after AoE II HD has been installed, there should be instructions for doing this in the wizard?

Also, I'm worried this game plays less smoothly in Phoenicis (POL 5) as opposed to POL 4 but I'm not sure how to test this because I'm not sure AoE II HD has the option to display an FPS counter. It's a bit worrying that Java's running in the background taking up 15% of my RAM on it's own, but I guess taking up RAM isn't really that much of an issue performance-wise. Hmm.

**Comment by plata** [comment]
I cannot reproduce this issue. The shortcut uses Steam to start the game which is working fine for me. If something needs to be done, `postInstall()` is the place where it should be (unless the file is only created after the first startup).

**Comment by Ads20000** [comment]
Really? That's really very weird, for me it does the 'installing pre-requisites' window fine but then the full screen AoE window doesn't load. Ubuntu 17.04.

**Comment by plata** [comment]
What happens if you open it manually via Steam?

**Comment by Ads20000** [comment]
@plata Errrr possible separate issue, how do I load Steam from Phoenicis after having only installed AoE II HD from the interface?

**Comment by plata** [comment]
When you run the AoE II HD shortcut from your library, Steam should start (because AoE is launched via Steam). So you should find the Steam icon in your task bar.

The 'run executable in container' is not implemented (yet).

**Comment by Ads20000** [comment]
@plata OK, I ran it from Steam as you said, still nothing. I have to rename AoK HD.exe to Launcher.exe and remove the old Launcher.exe for it to work.

**Comment by plata** [comment]
That's super strange. For me the launcher is starting:
![launcher](https://cloud.githubusercontent.com/assets/3973260/25773822/e902c8ce-3284-11e7-83a5-5aaffe887703.png)

Anyways the launcher is broken. So I think it would be ok to do the renaming all the time.

**Comment by Ads20000** [comment]
@plata Right, I have no idea how to write this into the script.

**Comment by plata** [comment]
Sure. I only get this if I don't edit the Launcher.exe. Don't think I have anything special installed. I'm currently trying if this can be done in the script. We'll know in some minutes.

**Comment by plata** [comment]
@Ads20000 can you try the fix?
