### ISSUE TITLE
Porting terraria script to POL5

### ISSUE THREAD

**Issue by nodiscc** [PlayOnLinux/Scripts#242]
Hello, I found a supposedly working terraria install script: https://github.com/lahtis/playonlinux/tree/master/working/terraria. I have no idea of how to port it to the new POL5 script format however.  If someone could point me to the right direction or send a patch adding Terraria it would be appreciated. I'd like to port more scripts in the future but don't know where to start.

**Comment by plata** [comment]
The script you linked is installing Terraria via Steam. To do this, we have a QuickScript. You can find a description about it in the [wiki](https://github.com/PlayOnLinux/Scripts/wiki/script.js#steamscript).
Some of the settings like `Set_OS "winxp"` can be done with [Wine settings](https://github.com/PlayOnLinux/Scripts/wiki/script.js#advanced) now. You need [Verbs](https://github.com/PlayOnLinux/Scripts/tree/master/Functions/Verbs) (see [pre-install hook](https://github.com/PlayOnLinux/Scripts/wiki/script.js#advanced))to install xinput and xna40 (they do not exist yet). However, the script is quite old so it might be that you do not need this anymore.
In general, it's always a good idea to look at the existing scripts. If you have any questions, feel free to ask.

**Comment by plata** [comment]
@nodiscc could you achieve something here or do you need more support?

**Comment by nodiscc** [comment]
@plata sorry for the late reply, I didn't start working on that script further than reading the doc, and it is currently low priority on my list :/ However your instructions were very helpful, now I know where to start. It would be nice if the PoL team could compile a list of resources about PoL scripting (examples, tutorials, helpers...) - maybe under _Help the project_ on https://www.playonlinux.com/en/?

Feel free to close this, or leave it open for reference; unfortunately I don't know when I'll be able to start.

**Comment by plata** [comment]
We are working on a new website. I collected your input in the issue for this: PlayOnLinux/POL-POM-5#557.

I will close the issue for now. However, feel free to open a new one or reopen this whenever you need more help.
