### ISSUE TITLE
required review

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#248]
@qparis do we want required reviews before merging to this repository (like we have for the software)?

**Comment by qparis** [comment]
Yeah, it is even more essential as scripts are not signed yet

**Comment by qparis** [comment]
(At least for non-trusted users)

**Comment by plata** [comment]
Ok. Do you set it up? Can you also give @madoar the rights to review?

**Comment by plata** [comment]
It's enabled now.
