### ISSUE TITLE
Write example for POL_Install_ equivalent

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#25]
Develop an example how DLL overrides etc. can be done with QuickScript. E.g. vcrun.

**Comment by qparis** [comment]
I think the callback should provide the wine instance as argument

**Comment by plata** [comment]
`go()` creates the wine instance. After `go()`, the installation is already finished. So I don't think that works.

**Comment by qparis** [comment]
Yes but the callback can still be passed. See the pull request coming

**Comment by qparis** [comment]
Should be good. See AC BortherHood script
