### ISSUE TITLE
DirectX 10

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/Scripts#276]
Can we add a verb for directx 10?
I need it for http://store.steampowered.com/app/342620/.
I'm not sure if this will help run the game, but at least some seems to got it working (https://www.reddit.com/r/linux_gaming/comments/3jyecw/what_are_some_of_the_best_games_you_can_run_in/)

**Comment by plata** [comment]
Sure we can. You can look at [winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks) (see load_d3dx10) to see how it can be done.

**Comment by madoar** [comment]
I already looked at it and I am kind of clueless how to write a script from it. 
Especially because I didn't find out where the directx 10 `dll` file comes from and what files it should contain and what to do with them afterwards...

**Comment by plata** [comment]
Seems like it's in `directx_Jun2010_redist`. Take a look at our DirectX 9 verb as a guideline.
