### ISSUE TITLE
No Games are visible in Apps

### ISSUE THREAD

**Issue by chriamue** [PlayOnLinux/Scripts#298]
When removing .Phoenicis/cache in home folder and after Refreshing Repositories in Settings,
no Games are visible in Apps anymore. Only Games from Oldwares repository are visible.
Notepad++ in Categorie Development for example is visible.

Tested on POL-POM-5 https://github.com/PlayOnLinux/POL-POM-5/commit/13e3898ef35e719ebf497793f91d68f7b042e9e7

**Comment by madoar** [comment]
Can you please start POL 5 via terminal and tell us if you get any errors?

**Comment by chriamue** [comment]
I don't think there are errors, but you can have a look into attached file.
[pol5-output.txt](https://github.com/PlayOnLinux/Scripts/files/1168074/pol5-output.txt)

**Comment by madoar** [comment]
Can you please take a look inside the folder `/home/chriamue/.Phoenicis/cache/git1703867752` and tell us what it contains?

**Comment by chriamue** [comment]
It contains the most recent scripts repository I think.
[git1703867752.txt](https://github.com/PlayOnLinux/Scripts/files/1168089/git1703867752.txt)

**Comment by plata** [comment]
Can we merge this with PlayOnLinux/POL-POM-5#957?

**Comment by chriamue** [comment]
Yes, it's the same problem.

**Comment by plata** [comment]
Ok, then I will close this one.
