### ISSUE TITLE
Silent steam installation

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#36]
Add some magic such that more of the installation happens in background.

* run Steam in background: add `-silent`.
* automatically close Steam when download is finished: see <https://github.com/akorb/SteamShutdown>

**Comment by qparis** [comment]
It would be awesome also if we could follow Steam download in a PlayOnLinux progressbar

**Comment by plata** [comment]
Yes. I'm trying to figure out something. But more importantly, we need to make sure that Steam is closed after the installation of Steam itself. Otherwise, the script will not continue which is not obvious at all.

**Comment by plata** [comment]
It seems like steam creates a metadata file `Steam/steamapps/appmanifest_${appId}.acf`

The SteamShutdown tool parses this file and checks the `StateFlags`. Apparently, the following values mean download:
* 1026
* 1042
* 1062
* 1030

This file also contains `BytesToDownload` and `BytesDownloaded` which should be fine for the progress bar. However, I had the impression, that `BytesDownloaded` is not updated.
