### ISSUE TITLE
Wine.getProgramFiles() returns string with line break at the end

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#4]

**Comment by qparis** [comment]
Hi ! Do you want to fix it? :)

**Comment by plata** [comment]
I can. But now I would like to have LocalApplicationsSource > GitApplicationsSource. Would be much easier to test changes in the scripts.

**Comment by qparis** [comment]
Why don't you override the system side settings?

**Comment by plata** [comment]
How?

**Comment by qparis** [comment]
Oh I see, ConfigApplicationSource needs to be implemented

**Comment by qparis** [comment]
(There is a ticket opened for that)

**Comment by plata** [comment]
I've seen that ticket. I mean I can easily change the order in the code. But I really think it would be better the other way around by default.

**Comment by qparis** [comment]
By default, it should be Local User Side > Internet > Local application side

**Comment by qparis** [comment]
This is why the ticket should be implemented to set this properly :)

**Comment by plata** [comment]
For me Local User Side is `${application.user.repository}`. So in fact we do not have Local application side currently and the Local User Side < Internet.

**Comment by qparis** [comment]
Yep, you are correct. This is why the two tickets need to be done :)
