### ISSUE TITLE
Wine steam installers stays at 0 bytes downloaded

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/Scripts#41]
See attached screenshot
<img width="1022" alt="capture d ecran 2017-01-01 a 22 20 46" src="https://cloud.githubusercontent.com/assets/373645/21583085/98417d48-d070-11e6-90b5-a2953dab65f2.png">

**Comment by plata** [comment]
Seems like every game uses a different folder structure. Moreover, Steam reserves the required disk space already at the beginning. Therefore the approach of using the disk space does not work.
I had tried with Hexcells. That seemed to work...

**Comment by plata** [comment]
see: fix SteamScript progress bar #47
