### ISSUE TITLE
Translate strings of the wizard

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#49]
We could use <http://www.localeplanet.com/> and <https://docs.transifex.com/formats/json>.

**Comment by plata** [comment]
Maybe: <https://github.com/adrienrn/jsgettext>

**Comment by plata** [comment]
Another possibility would be to call `tr` directly:
```Javascript
Packages.org.phoenicis.configuration.localisation.Localisation.tr("translation test.")
```

This is working but I'm not sure how we can get the text into our `.pot` and `.po` files (especially for user repositories).

**Comment by qparis** [comment]
Called tr directly makes more sense. The analysis of the scripts is another problem we can handle quite easily

**Comment by plata** [comment]
If we do that, all strings have to be in the properties file which is generated with `mvn gettext:dist`. I don't see how this should happen for user repositories.

**Comment by qparis** [comment]
The pot files should not necessarily be generated by maven. 
We could imagine another process that could generate all the translations from all our git repositories and uploading them to a translation platform. 
This is the way it is done in POLv4

**Comment by plata** [comment]
Sure. But that's still not enough. For example, I could provide my own scripts in a separate repository. In this case, I would not have any chance to translate those.

**Comment by qparis** [comment]
You could add your translation to the main repository, it should work fine

**Comment by plata** [comment]
Doesn't that defeat the whole point of custom repositories? I might not even want my strings to be available publicly (e.g. in a company environment). With a solution which loads a json with the translations at runtime, I could provide my own translation file for my repository.

**Comment by qparis** [comment]
Correct

**Comment by qparis** [comment]
Then we should also allow to include po files in a repository

**Comment by plata** [comment]
Yes.

**Comment by plata** [comment]
The problem with the solution from localeplanet is that it seems to do only a simple mapping. So no plural forms etc.

**Comment by plata** [comment]
I managed to get i18next running after changing the [i18next.js](https://unpkg.com/i18next/i18next.js) a little bit. So I guess we could use that.
However, there's still another problem: How do we translate the `.json` files?

**Comment by plata** [comment]
I opened a PR (PlayOnLinux/POL-POM-5#870) to solve the `.json` translation).

**Comment by plata** [comment]
Fixed.
