### ISSUE TITLE
Enhance InstallerScript for local files

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/Scripts#88]
The InstallerScript shall be able to handle a local file which is selected in a browse step.

**Comment by qparis** [comment]
For me it should be a different quick script

**Comment by plata** [comment]
Really? For me the definition of InstallerScript is to install a given executable. I would have done it like this:
```javascript
if (this._url) {
  new Downloader()...
} else {
  setupWizard.browse();
}
```

**Comment by qparis** [comment]
Why using conditions when you can take advantage of inheritance and abstraction? :-)

**Comment by plata** [comment]
I don't see how the `go()` method could be implemented with inheritance without duplicating most of the code in it.

**Comment by qparis** [comment]
Download is providing an absolute path to a file, same for browse()

This is the only one difference between the two quick scripts. I think we can create a protected method that process the installation from an absolute file

**Comment by plata** [comment]
Ok. So we have LocalInstallerScript and RemoteInstallerScript inheriting from InstallerScript. InstallerScript gets a method `installationFile()`. But how to show the browse dialog in LocalInstallerScript if the `go()` shall be implemented in InstallerScript?

**Comment by qparis** [comment]
It should be a callback property

**Comment by plata** [comment]
I see. Yes that should work. I will give it a try.
